# Generated by Django 4.1.7 on 2023-03-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questionmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='bank',
        ),
    ]
