# Generated by Django 4.1.7 on 2023-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_questionmodel_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='isMultipleChoice',
            field=models.BooleanField(blank=True),
        ),
    ]
