# Generated by Django 4.1.7 on 2023-03-26 07:48

import banks.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('file_url', models.FileField(blank=True, null=True, upload_to=banks.models.upload_to)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['-createdAt'],
            },
        ),
    ]
